# -*- coding: utf-8 -*-
"""Personalized Text Summarizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/personalized-text-summarizer-9e4c0224-57f9-4792-a4f1-4d8a991c5e76.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20240827/auto/storage/goog4_request%26X-Goog-Date%3D20240827T022853Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Dbb3151f6e9bcb4ade9fccbec19d2ee0d581f98d96043ed94b5222bc451675d46021bdd7cb545d5d2c4b87025877a6328844ab9c99c72417058291382cd5d0544ed8af01c6e98668a3a2955b21095d40f28287d44ac1e0e1170175a4813f915f26037132f7823660894e9da0c972064bde0a96ff4029a125ae00064cdffe3e0b110e671c6acc46af93ccad1d599a2fce9e88dad99bfc866d0f53367edd141ceb1b0857736bf0326903ab69da1a0c6dc9291ba6f8bee0358de1d3c10603011d8b438c976ab6db960854d3b80d3cdc70db124c5ddb80005a9c3e6c7b9aff09fc54b5646ced2747a4c6ccdc5c41c2db37c20673adc3b09d62c209877245c6e328d37
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

pip install streamlit

pip install transformers

pip install nltk

pip install spacy

from transformers import pipeline

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

import streamlit as st

# Title of the Streamlit app
st.title("Personalized Text Summarizer")

# Text area for input
text_input = st.text_area("Enter the text you want to summarize:")

# Slider for summary length
summary_length = st.slider("Select the summary length:", min_value=10, max_value=500, value=100)

# Dropdown for summary focus (e.g., key points, specific details)
focus_area = st.selectbox("Select the focus area:", ["Key Points", "Specific Details", "General Overview"])

# Button to generate the summary
if st.button("Summarize"):
    if text_input:
        # Generate summary based on user input
        summary = summarizer(text_input, max_length=summary_length, min_length=summary_length//2, do_sample=False)[0]['summary_text']

        # Display the summary
        st.subheader("Summary:")
        st.write(summary)
    else:
        st.warning("Please enter some text to summarize.")

if focus_area == "Key Points":
    summary = summarizer(text_input, max_length=summary_length, min_length=summary_length//2, do_sample=False, num_beams=4)[0]['summary_text']
elif focus_area == "Specific Details":
    summary = summarizer(text_input, max_length=summary_length, min_length=summary_length//2, do_sample=True, top_k=50)[0]['summary_text']
elif focus_area == "General Overview":
    summary = summarizer(text_input, max_length=summary_length, min_length=summary_length//2, do_sample=False, num_return_sequences=1)[0]['summary_text']



